import json

MEALS_SEED = [
    # ===== BREAKFAST =====
    {
        "name": "Bacon & Egg Bowl",
        "description": "Crispy bacon strips with fried eggs and melted cheese — the ultimate carnivore breakfast.",
        "image_url": "https://keto-creator.vercel.app/meals/bacon-egg-bowl.jpg",
        "diet_type": "both",
        "meal_type": "breakfast",
        "prep_time_mins": 5,
        "cook_time_mins": 10,
        "servings": 1,
        "calories": 620,
        "fat_g": 52,
        "protein_g": 38,
        "carbs_g": 1,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Bacon strips", "amount": "4", "unit": "strips"},
            {"name": "Eggs", "amount": "3", "unit": "large"},
            {"name": "Cheddar cheese", "amount": "30", "unit": "g"},
            {"name": "Butter", "amount": "1", "unit": "tbsp"},
        ]),
        "instructions": json.dumps([
            "Cook bacon in a pan over medium heat until crispy, about 4-5 minutes per side.",
            "Remove bacon and cook eggs in the same pan with butter.",
            "Top eggs with shredded cheddar and cover pan for 1 minute to melt cheese.",
            "Serve alongside the crispy bacon.",
        ]),
        "tags": json.dumps(["quick", "high-protein", "carnivore"]),
        "allergens": json.dumps(["dairy", "eggs"]),
        "cost_estimate": 4.5,
    },
    {
        "name": "Keto Avocado Eggs",
        "description": "Baked eggs inside creamy avocado halves with a sprinkle of paprika.",
        "image_url": "https://keto-creator.vercel.app/meals/keto-avocado-eggs.jpg",
        "diet_type": "keto",
        "meal_type": "breakfast",
        "prep_time_mins": 5,
        "cook_time_mins": 15,
        "servings": 1,
        "calories": 450,
        "fat_g": 40,
        "protein_g": 16,
        "carbs_g": 4,
        "fiber_g": 7,
        "ingredients": json.dumps([
            {"name": "Avocado", "amount": "1", "unit": "large"},
            {"name": "Eggs", "amount": "2", "unit": "large"},
            {"name": "Smoked paprika", "amount": "1/4", "unit": "tsp"},
            {"name": "Salt & pepper", "amount": "to taste", "unit": ""},
        ]),
        "instructions": json.dumps([
            "Preheat oven to 200°C. Halve avocado and remove pit, scooping out a bit more flesh.",
            "Place avocado halves in a baking dish and crack one egg into each.",
            "Season with paprika, salt and pepper.",
            "Bake for 12-15 minutes until whites are set but yolk still runny.",
        ]),
        "tags": json.dumps(["baked", "vegetarian-keto", "quick"]),
        "allergens": json.dumps(["eggs"]),
        "cost_estimate": 3.0,
    },
    {
        "name": "Steak & Eggs",
        "description": "Ribeye steak cooked to perfection paired with sunny-side eggs.",
        "image_url": "https://keto-creator.vercel.app/meals/steak-and-eggs.jpg",
        "diet_type": "both",
        "meal_type": "breakfast",
        "prep_time_mins": 5,
        "cook_time_mins": 12,
        "servings": 1,
        "calories": 780,
        "fat_g": 58,
        "protein_g": 62,
        "carbs_g": 0,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Ribeye steak", "amount": "200", "unit": "g"},
            {"name": "Eggs", "amount": "2", "unit": "large"},
            {"name": "Butter", "amount": "2", "unit": "tbsp"},
            {"name": "Salt & pepper", "amount": "to taste", "unit": ""},
        ]),
        "instructions": json.dumps([
            "Season steak generously with salt and pepper.",
            "Heat a cast iron pan over high heat, add butter when hot.",
            "Cook steak 3-4 min per side for medium-rare. Rest 3 minutes.",
            "In same pan, fry eggs sunny-side up.",
            "Slice steak and serve with eggs.",
        ]),
        "tags": json.dumps(["carnivore", "high-protein", "premium"]),
        "allergens": json.dumps(["dairy", "eggs"]),
        "cost_estimate": 12.0,
    },
    {
        "name": "Keto Smoothie Bowl",
        "description": "Thick coconut cream smoothie topped with berries, seeds and nuts.",
        "image_url": "https://keto-creator.vercel.app/meals/keto-smoothie-bowl.jpg",
        "diet_type": "keto",
        "meal_type": "breakfast",
        "prep_time_mins": 10,
        "cook_time_mins": 0,
        "servings": 1,
        "calories": 420,
        "fat_g": 38,
        "protein_g": 12,
        "carbs_g": 8,
        "fiber_g": 5,
        "ingredients": json.dumps([
            {"name": "Coconut cream", "amount": "150", "unit": "ml"},
            {"name": "Raspberries", "amount": "50", "unit": "g"},
            {"name": "Almond butter", "amount": "2", "unit": "tbsp"},
            {"name": "Chia seeds", "amount": "1", "unit": "tbsp"},
            {"name": "Collagen powder", "amount": "1", "unit": "scoop"},
        ]),
        "instructions": json.dumps([
            "Blend coconut cream, half the raspberries, almond butter and collagen until thick.",
            "Pour into a bowl.",
            "Top with remaining raspberries, chia seeds.",
        ]),
        "tags": json.dumps(["no-cook", "keto", "dairy-free"]),
        "allergens": json.dumps(["tree-nuts"]),
        "cost_estimate": 5.0,
    },
    {
        "name": "Carnivore Sausage Scramble",
        "description": "Pork sausages scrambled with eggs and beef tallow.",
        "image_url": "https://keto-creator.vercel.app/meals/carnivore-sausage-scramble.jpg",
        "diet_type": "both",
        "meal_type": "breakfast",
        "prep_time_mins": 5,
        "cook_time_mins": 10,
        "servings": 1,
        "calories": 690,
        "fat_g": 55,
        "protein_g": 45,
        "carbs_g": 1,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Pork sausages", "amount": "2", "unit": "links"},
            {"name": "Eggs", "amount": "3", "unit": "large"},
            {"name": "Beef tallow", "amount": "1", "unit": "tbsp"},
            {"name": "Salt", "amount": "to taste", "unit": ""},
        ]),
        "instructions": json.dumps([
            "Slice sausages into rounds and cook in beef tallow over medium heat.",
            "Whisk eggs and pour over sausages.",
            "Scramble gently until just set. Season and serve.",
        ]),
        "tags": json.dumps(["carnivore", "quick", "high-protein"]),
        "allergens": json.dumps(["eggs"]),
        "cost_estimate": 5.5,
    },

    # ===== LUNCH =====
    {
        "name": "Ribeye Steak Salad",
        "description": "Sliced ribeye over arugula with parmesan shavings and olive oil dressing.",
        "image_url": "https://keto-creator.vercel.app/meals/ribeye-steak-salad.jpg",
        "diet_type": "keto",
        "meal_type": "lunch",
        "prep_time_mins": 10,
        "cook_time_mins": 12,
        "servings": 1,
        "calories": 680,
        "fat_g": 52,
        "protein_g": 48,
        "carbs_g": 3,
        "fiber_g": 2,
        "ingredients": json.dumps([
            {"name": "Ribeye steak", "amount": "180", "unit": "g"},
            {"name": "Arugula", "amount": "60", "unit": "g"},
            {"name": "Parmesan", "amount": "20", "unit": "g"},
            {"name": "Olive oil", "amount": "3", "unit": "tbsp"},
            {"name": "Lemon juice", "amount": "1", "unit": "tbsp"},
        ]),
        "instructions": json.dumps([
            "Cook ribeye to desired doneness, rest and slice thin.",
            "Toss arugula with olive oil and lemon juice.",
            "Top with steak slices and parmesan shavings.",
        ]),
        "tags": json.dumps(["salad", "keto", "premium"]),
        "allergens": json.dumps(["dairy"]),
        "cost_estimate": 13.0,
    },
    {
        "name": "Ground Beef Bowl",
        "description": "Seasoned ground beef with butter-sautéed mushrooms and a fried egg on top.",
        "image_url": "https://keto-creator.vercel.app/meals/ground-beef-bowl.jpg",
        "diet_type": "both",
        "meal_type": "lunch",
        "prep_time_mins": 5,
        "cook_time_mins": 15,
        "servings": 1,
        "calories": 720,
        "fat_g": 56,
        "protein_g": 50,
        "carbs_g": 2,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Ground beef (80/20)", "amount": "200", "unit": "g"},
            {"name": "Mushrooms", "amount": "80", "unit": "g"},
            {"name": "Butter", "amount": "2", "unit": "tbsp"},
            {"name": "Egg", "amount": "1", "unit": "large"},
            {"name": "Garlic powder", "amount": "1/2", "unit": "tsp"},
        ]),
        "instructions": json.dumps([
            "Brown ground beef in a pan over high heat, breaking apart. Season with garlic powder and salt.",
            "In another pan, sauté mushrooms in butter until golden.",
            "Fry the egg in same pan.",
            "Assemble bowl: beef, mushrooms, topped with egg.",
        ]),
        "tags": json.dumps(["carnivore", "bowl", "quick"]),
        "allergens": json.dumps(["dairy", "eggs"]),
        "cost_estimate": 7.0,
    },
    {
        "name": "Chicken Thigh & Avocado Plate",
        "description": "Crispy skin chicken thighs with sliced avocado and a herb butter sauce.",
        "image_url": "https://keto-creator.vercel.app/meals/chicken-thigh-avocado.jpg",
        "diet_type": "keto",
        "meal_type": "lunch",
        "prep_time_mins": 5,
        "cook_time_mins": 25,
        "servings": 1,
        "calories": 640,
        "fat_g": 50,
        "protein_g": 44,
        "carbs_g": 4,
        "fiber_g": 3,
        "ingredients": json.dumps([
            {"name": "Chicken thighs (skin-on)", "amount": "2", "unit": "pieces"},
            {"name": "Avocado", "amount": "1", "unit": "medium"},
            {"name": "Butter", "amount": "2", "unit": "tbsp"},
            {"name": "Fresh thyme", "amount": "3", "unit": "sprigs"},
            {"name": "Garlic", "amount": "2", "unit": "cloves"},
        ]),
        "instructions": json.dumps([
            "Season chicken thighs with salt and pepper.",
            "Cook skin-side down in an oven-safe pan for 12 minutes over medium-high heat.",
            "Flip, add butter, garlic and thyme. Baste and finish in 200°C oven for 10 minutes.",
            "Serve with sliced avocado and pan juices drizzled over.",
        ]),
        "tags": json.dumps(["keto", "crispy", "high-protein"]),
        "allergens": json.dumps(["dairy"]),
        "cost_estimate": 8.0,
    },
    {
        "name": "Tuna Lettuce Wraps",
        "description": "Wild tuna mixed with mayo and celery, wrapped in butter lettuce.",
        "image_url": "https://keto-creator.vercel.app/meals/tuna-lettuce-wraps.jpg",
        "diet_type": "keto",
        "meal_type": "lunch",
        "prep_time_mins": 10,
        "cook_time_mins": 0,
        "servings": 1,
        "calories": 380,
        "fat_g": 28,
        "protein_g": 30,
        "carbs_g": 3,
        "fiber_g": 1,
        "ingredients": json.dumps([
            {"name": "Canned tuna in oil", "amount": "150", "unit": "g"},
            {"name": "Mayonnaise", "amount": "3", "unit": "tbsp"},
            {"name": "Celery stalk", "amount": "1", "unit": "stalk"},
            {"name": "Butter lettuce leaves", "amount": "4", "unit": "leaves"},
            {"name": "Lemon juice", "amount": "1", "unit": "tsp"},
        ]),
        "instructions": json.dumps([
            "Drain tuna and mix with mayo, diced celery, and lemon juice.",
            "Season with salt and pepper.",
            "Spoon mixture into lettuce leaves and serve.",
        ]),
        "tags": json.dumps(["no-cook", "quick", "light", "dairy-free"]),
        "allergens": json.dumps(["fish", "eggs"]),
        "cost_estimate": 4.0,
    },
    {
        "name": "Bone Broth Beef Stew",
        "description": "Rich beef stew cooked in bone broth with carrots and celery.",
        "image_url": "https://keto-creator.vercel.app/meals/bone-broth-beef-stew.jpg",
        "diet_type": "carnivore",
        "meal_type": "lunch",
        "prep_time_mins": 15,
        "cook_time_mins": 90,
        "servings": 2,
        "calories": 520,
        "fat_g": 28,
        "protein_g": 55,
        "carbs_g": 4,
        "fiber_g": 1,
        "ingredients": json.dumps([
            {"name": "Beef chuck", "amount": "400", "unit": "g"},
            {"name": "Bone broth", "amount": "500", "unit": "ml"},
            {"name": "Celery", "amount": "2", "unit": "stalks"},
            {"name": "Beef tallow", "amount": "2", "unit": "tbsp"},
            {"name": "Bay leaves", "amount": "2", "unit": "leaves"},
        ]),
        "instructions": json.dumps([
            "Cut beef into large chunks and sear in tallow over high heat until browned.",
            "Add bone broth, celery and bay leaves. Bring to boil.",
            "Reduce heat, cover and simmer for 90 minutes until beef is tender.",
            "Season with salt and serve.",
        ]),
        "tags": json.dumps(["carnivore", "slow-cook", "meal-prep"]),
        "allergens": json.dumps([]),
        "cost_estimate": 9.0,
    },
    {
        "name": "Salmon Avocado Bowl",
        "description": "Pan-seared salmon fillet over sliced avocado with lemon butter.",
        "image_url": "https://keto-creator.vercel.app/meals/salmon-avocado-bowl.jpg",
        "diet_type": "keto",
        "meal_type": "lunch",
        "prep_time_mins": 5,
        "cook_time_mins": 10,
        "servings": 1,
        "calories": 590,
        "fat_g": 46,
        "protein_g": 42,
        "carbs_g": 4,
        "fiber_g": 3,
        "ingredients": json.dumps([
            {"name": "Salmon fillet", "amount": "180", "unit": "g"},
            {"name": "Avocado", "amount": "1", "unit": "medium"},
            {"name": "Butter", "amount": "2", "unit": "tbsp"},
            {"name": "Lemon", "amount": "1/2", "unit": "lemon"},
            {"name": "Dill", "amount": "1", "unit": "tbsp"},
        ]),
        "instructions": json.dumps([
            "Season salmon with salt and pepper.",
            "Pan-sear in butter skin-side up for 3 minutes, flip and cook 2 more minutes.",
            "Add lemon juice and dill to pan to make quick sauce.",
            "Serve over sliced avocado with sauce drizzled on top.",
        ]),
        "tags": json.dumps(["omega-3", "keto", "quick"]),
        "allergens": json.dumps(["fish", "dairy"]),
        "cost_estimate": 11.0,
    },

    # ===== DINNER =====
    {
        "name": "New York Strip with Herb Butter",
        "description": "Perfectly seared NY strip steak topped with garlic herb butter.",
        "image_url": "https://keto-creator.vercel.app/meals/ny-strip-herb-butter.jpg",
        "diet_type": "both",
        "meal_type": "dinner",
        "prep_time_mins": 10,
        "cook_time_mins": 12,
        "servings": 1,
        "calories": 820,
        "fat_g": 62,
        "protein_g": 65,
        "carbs_g": 1,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "NY Strip steak", "amount": "250", "unit": "g"},
            {"name": "Butter", "amount": "3", "unit": "tbsp"},
            {"name": "Garlic", "amount": "3", "unit": "cloves"},
            {"name": "Fresh rosemary", "amount": "2", "unit": "sprigs"},
            {"name": "Thyme", "amount": "3", "unit": "sprigs"},
        ]),
        "instructions": json.dumps([
            "Bring steak to room temperature. Season generously with salt and pepper.",
            "Heat cast iron skillet over high heat until smoking.",
            "Add steak, cook 3-4 min per side for medium-rare.",
            "Last minute: add butter, garlic, rosemary, thyme. Baste steak continuously.",
            "Rest 5 minutes before slicing.",
        ]),
        "tags": json.dumps(["carnivore", "premium", "keto"]),
        "allergens": json.dumps(["dairy"]),
        "cost_estimate": 18.0,
    },
    {
        "name": "Creamy Garlic Butter Shrimp",
        "description": "Jumbo shrimp in a rich garlic cream sauce with parmesan.",
        "image_url": "https://keto-creator.vercel.app/meals/creamy-garlic-shrimp.jpg",
        "diet_type": "keto",
        "meal_type": "dinner",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 1,
        "calories": 560,
        "fat_g": 42,
        "protein_g": 40,
        "carbs_g": 4,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Jumbo shrimp", "amount": "200", "unit": "g"},
            {"name": "Heavy cream", "amount": "100", "unit": "ml"},
            {"name": "Butter", "amount": "3", "unit": "tbsp"},
            {"name": "Garlic", "amount": "4", "unit": "cloves"},
            {"name": "Parmesan", "amount": "30", "unit": "g"},
        ]),
        "instructions": json.dumps([
            "Sauté garlic in butter until fragrant, about 1 minute.",
            "Add shrimp, cook 2 minutes per side until pink.",
            "Pour in heavy cream and simmer until slightly thickened.",
            "Stir in parmesan and season to taste.",
        ]),
        "tags": json.dumps(["keto", "seafood", "creamy"]),
        "allergens": json.dumps(["shellfish", "dairy"]),
        "cost_estimate": 14.0,
    },
    {
        "name": "Pork Belly Strips",
        "description": "Slow-roasted pork belly strips with crispy crackling.",
        "image_url": "https://keto-creator.vercel.app/meals/pork-belly-strips.jpg",
        "diet_type": "both",
        "meal_type": "dinner",
        "prep_time_mins": 10,
        "cook_time_mins": 120,
        "servings": 2,
        "calories": 750,
        "fat_g": 65,
        "protein_g": 38,
        "carbs_g": 0,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Pork belly", "amount": "400", "unit": "g"},
            {"name": "Salt", "amount": "2", "unit": "tsp"},
            {"name": "Fennel seeds", "amount": "1", "unit": "tsp"},
            {"name": "Garlic powder", "amount": "1", "unit": "tsp"},
        ]),
        "instructions": json.dumps([
            "Score pork belly skin deeply. Rub with salt, fennel and garlic powder.",
            "Roast skin-side up at 160°C for 90 minutes.",
            "Increase to 220°C for final 20 minutes for crispy crackling.",
            "Rest 10 minutes before slicing.",
        ]),
        "tags": json.dumps(["carnivore", "slow-cook", "meal-prep"]),
        "allergens": json.dumps([]),
        "cost_estimate": 10.0,
    },
    {
        "name": "Lamb Chops with Rosemary",
        "description": "Grilled lamb chops marinated in garlic and rosemary.",
        "image_url": "https://keto-creator.vercel.app/meals/lamb-chops-rosemary.jpg",
        "diet_type": "both",
        "meal_type": "dinner",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 1,
        "calories": 680,
        "fat_g": 50,
        "protein_g": 52,
        "carbs_g": 1,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Lamb chops", "amount": "3", "unit": "chops"},
            {"name": "Rosemary", "amount": "3", "unit": "sprigs"},
            {"name": "Garlic", "amount": "3", "unit": "cloves"},
            {"name": "Olive oil", "amount": "2", "unit": "tbsp"},
            {"name": "Salt & pepper", "amount": "to taste", "unit": ""},
        ]),
        "instructions": json.dumps([
            "Marinate lamb chops with crushed garlic, rosemary and olive oil for 30 min.",
            "Grill or pan-sear on high heat, 3 minutes per side for medium.",
            "Rest 5 minutes. Season and serve.",
        ]),
        "tags": json.dumps(["carnivore", "grilled", "premium"]),
        "allergens": json.dumps([]),
        "cost_estimate": 16.0,
    },
    {
        "name": "Keto Zucchini Lasagna",
        "description": "Classic lasagna layers using thin zucchini slices instead of pasta.",
        "image_url": "https://keto-creator.vercel.app/meals/keto-zucchini-lasagna.jpg",
        "diet_type": "keto",
        "meal_type": "dinner",
        "prep_time_mins": 20,
        "cook_time_mins": 45,
        "servings": 4,
        "calories": 480,
        "fat_g": 32,
        "protein_g": 38,
        "carbs_g": 8,
        "fiber_g": 2,
        "ingredients": json.dumps([
            {"name": "Zucchini", "amount": "3", "unit": "large"},
            {"name": "Ground beef", "amount": "400", "unit": "g"},
            {"name": "Ricotta cheese", "amount": "250", "unit": "g"},
            {"name": "Mozzarella", "amount": "150", "unit": "g"},
            {"name": "Crushed tomatoes", "amount": "400", "unit": "g"},
            {"name": "Italian seasoning", "amount": "2", "unit": "tsp"},
        ]),
        "instructions": json.dumps([
            "Slice zucchini thinly lengthwise. Salt and let drain 10 minutes.",
            "Brown ground beef with Italian seasoning. Add crushed tomatoes and simmer 10 min.",
            "Layer: zucchini, beef sauce, ricotta. Repeat. Top with mozzarella.",
            "Bake at 190°C for 35 minutes. Rest 10 minutes before serving.",
        ]),
        "tags": json.dumps(["keto", "meal-prep", "comfort-food"]),
        "allergens": json.dumps(["dairy"]),
        "cost_estimate": 12.0,
    },
    {
        "name": "Butter Chicken (Keto)",
        "description": "Creamy tomato-spiced chicken thighs in a rich butter sauce.",
        "image_url": "https://keto-creator.vercel.app/meals/butter-chicken-keto.jpg",
        "diet_type": "keto",
        "meal_type": "dinner",
        "prep_time_mins": 15,
        "cook_time_mins": 30,
        "servings": 2,
        "calories": 580,
        "fat_g": 42,
        "protein_g": 44,
        "carbs_g": 7,
        "fiber_g": 1,
        "ingredients": json.dumps([
            {"name": "Chicken thighs (boneless)", "amount": "400", "unit": "g"},
            {"name": "Heavy cream", "amount": "150", "unit": "ml"},
            {"name": "Crushed tomatoes", "amount": "200", "unit": "g"},
            {"name": "Butter", "amount": "3", "unit": "tbsp"},
            {"name": "Garam masala", "amount": "2", "unit": "tsp"},
            {"name": "Ginger-garlic paste", "amount": "1", "unit": "tbsp"},
        ]),
        "instructions": json.dumps([
            "Brown chicken in butter over high heat. Remove and set aside.",
            "Sauté ginger-garlic paste, add garam masala, cook 1 minute.",
            "Add crushed tomatoes, simmer 10 minutes.",
            "Return chicken to pan, add heavy cream. Simmer 15 minutes.",
        ]),
        "tags": json.dumps(["keto", "spiced", "comfort-food", "meal-prep"]),
        "allergens": json.dumps(["dairy"]),
        "cost_estimate": 9.0,
    },
    {
        "name": "Organ Meat Patties",
        "description": "Nutritious beef liver and heart patties, carnivore staple.",
        "image_url": "https://keto-creator.vercel.app/meals/organ-meat-patties.jpg",
        "diet_type": "carnivore",
        "meal_type": "dinner",
        "prep_time_mins": 15,
        "cook_time_mins": 12,
        "servings": 2,
        "calories": 520,
        "fat_g": 28,
        "protein_g": 62,
        "carbs_g": 2,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Ground beef", "amount": "250", "unit": "g"},
            {"name": "Beef liver", "amount": "100", "unit": "g"},
            {"name": "Beef heart", "amount": "100", "unit": "g"},
            {"name": "Tallow", "amount": "1", "unit": "tbsp"},
            {"name": "Salt", "amount": "1", "unit": "tsp"},
        ]),
        "instructions": json.dumps([
            "Finely grind or food-process liver and heart.",
            "Mix all meat together with salt. Form into 4 patties.",
            "Cook in tallow over medium-high heat, 4-5 minutes per side.",
            "Rest 3 minutes before serving.",
        ]),
        "tags": json.dumps(["carnivore", "organ-meat", "nutrient-dense"]),
        "allergens": json.dumps([]),
        "cost_estimate": 6.0,
    },

    # ===== SNACKS =====
    {
        "name": "Beef Jerky (Homemade)",
        "description": "Lean beef sliced thin and dried with simple spices. Zero carbs.",
        "image_url": "https://keto-creator.vercel.app/meals/beef-jerky.jpg",
        "diet_type": "both",
        "meal_type": "snack",
        "prep_time_mins": 15,
        "cook_time_mins": 240,
        "servings": 4,
        "calories": 220,
        "fat_g": 8,
        "protein_g": 34,
        "carbs_g": 1,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Lean beef (eye of round)", "amount": "500", "unit": "g"},
            {"name": "Salt", "amount": "2", "unit": "tsp"},
            {"name": "Black pepper", "amount": "1", "unit": "tsp"},
            {"name": "Garlic powder", "amount": "1", "unit": "tsp"},
        ]),
        "instructions": json.dumps([
            "Slice beef 3mm thin against the grain.",
            "Rub with salt, pepper and garlic powder.",
            "Place on wire rack on baking sheet.",
            "Dry in oven at 70°C for 4 hours until dry but slightly pliable.",
        ]),
        "tags": json.dumps(["carnivore", "portable", "meal-prep"]),
        "allergens": json.dumps([]),
        "cost_estimate": 8.0,
    },
    {
        "name": "Cheese Crisps",
        "description": "Baked parmesan rounds that crisp up perfectly for keto snacking.",
        "image_url": "https://keto-creator.vercel.app/meals/cheese-crisps.jpg",
        "diet_type": "keto",
        "meal_type": "snack",
        "prep_time_mins": 2,
        "cook_time_mins": 8,
        "servings": 1,
        "calories": 220,
        "fat_g": 16,
        "protein_g": 18,
        "carbs_g": 1,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Parmesan (finely grated)", "amount": "60", "unit": "g"},
            {"name": "Paprika or Italian herbs", "amount": "1/2", "unit": "tsp"},
        ]),
        "instructions": json.dumps([
            "Preheat oven to 190°C. Line baking sheet with parchment.",
            "Mound tablespoon portions of parmesan on sheet, press flat.",
            "Sprinkle with seasoning. Bake 7-8 minutes until golden.",
            "Cool completely before eating — they crisp as they cool.",
        ]),
        "tags": json.dumps(["keto", "quick", "crunchy"]),
        "allergens": json.dumps(["dairy"]),
        "cost_estimate": 2.0,
    },
    {
        "name": "Hard Boiled Eggs & Bacon",
        "description": "Simple portable snack: hard-boiled eggs wrapped in crispy bacon.",
        "image_url": "https://keto-creator.vercel.app/meals/hard-boiled-eggs-bacon.jpg",
        "diet_type": "both",
        "meal_type": "snack",
        "prep_time_mins": 2,
        "cook_time_mins": 12,
        "servings": 1,
        "calories": 310,
        "fat_g": 24,
        "protein_g": 22,
        "carbs_g": 0,
        "fiber_g": 0,
        "ingredients": json.dumps([
            {"name": "Eggs", "amount": "2", "unit": "large"},
            {"name": "Bacon strips", "amount": "2", "unit": "strips"},
        ]),
        "instructions": json.dumps([
            "Boil eggs for 10-12 minutes. Cool in ice water, peel.",
            "Cook bacon until crispy. Wrap around eggs and secure with toothpick.",
        ]),
        "tags": json.dumps(["carnivore", "portable", "quick"]),
        "allergens": json.dumps(["eggs"]),
        "cost_estimate": 2.0,
    },
    {
        "name": "Almond Butter Fat Bombs",
        "description": "Frozen keto fat bombs with almond butter and coconut oil.",
        "image_url": "https://keto-creator.vercel.app/meals/almond-butter-fat-bombs.jpg",
        "diet_type": "keto",
        "meal_type": "snack",
        "prep_time_mins": 10,
        "cook_time_mins": 30,
        "servings": 6,
        "calories": 190,
        "fat_g": 18,
        "protein_g": 4,
        "carbs_g": 3,
        "fiber_g": 1,
        "ingredients": json.dumps([
            {"name": "Almond butter", "amount": "120", "unit": "g"},
            {"name": "Coconut oil", "amount": "60", "unit": "g"},
            {"name": "Vanilla extract", "amount": "1", "unit": "tsp"},
            {"name": "Pinch of salt", "amount": "1", "unit": "pinch"},
        ]),
        "instructions": json.dumps([
            "Melt coconut oil and mix with almond butter, vanilla and salt.",
            "Pour into silicone molds or ice cube trays.",
            "Freeze for 30 minutes until solid.",
            "Store in freezer, eat straight from frozen.",
        ]),
        "tags": json.dumps(["keto", "fat-bomb", "meal-prep", "sweet"]),
        "allergens": json.dumps(["tree-nuts"]),
        "cost_estimate": 3.0,
    },
]
